name: 🚀 Space Shooter Game

on:
  schedule:
    - cron: "0 6 * * *" # todos los días a las 00:00 Guatemala (06:00 UTC)
  workflow_dispatch: # permite ejecutarlo manualmente desde la pestaña Actions

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: czl9707/gh-space-shooter@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-path: "game.gif"
          strategy: "random"
